# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floody', '0002_auto_20171208_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='onwer',
            new_name='owner',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
