# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floody', '0006_auto_20171209_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='uploaded/'),
        ),
    ]
